language: scala

scala:
  - 2.10.6
  - 2.11.11

jdk:
  - oraclejdk8

env:

matrix:
  # Add a job for 2.12 which publishes the site
  include:
  - scala: 2.12.4
    env: PUBLISH_SITE=true

before_install:
 - if [ "$PUBLISH_SITE" = "true" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
   scripts/decryptKeys.sh; fi
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean headerCheck compile tut coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$PUBLISH_SITE" = "true" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
    scripts/publishMicrosite.sh; fi
  - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" && $(cat version.sbt) =~ "-SNAPSHOT" ]]; then bash
    scripts/publishSnapshot.sh; fi

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier

