language: scala

scala:
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk8

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile tut coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
